apiVersion: apps/v1
kind: Deployment
metadata:
  name: orphanslife
spec:
  selector:
    matchLabels:
      app: orphanslife
  replicas: 1
  template:
    metadata:
      labels:
        app: orphanslife
    spec:
      containers:
        - name: orphanslife
          image: deepakkaligotla/orphanslife:0.0.1.RELEASE
          resources: {}
          ports:
            - containerPort: 4000
status: {}