apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: orphanslife
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000