# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'orphanslife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0'
  pod 'AlamofireImage', '~> 4.1'

end
